# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'relay.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import *


class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(600, 500)
                MainWindow.setMinimumSize(QtCore.QSize(600, 500))
                MainWindow.setMaximumSize(QtCore.QSize(600, 500))
                MainWindow.setWindowOpacity(1.0)
                MainWindow.setStyleSheet("background-color: #303030;")
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")

                #frame
                self.frameChat = QtWidgets.QFrame(self.centralwidget)
                self.frameChat.setGeometry(QtCore.QRect(0, -29, 601, 511))
                self.frameChat.setStyleSheet("background-color: red;\n")
                self.frameChat.setFrameShadow(QtWidgets.QFrame.Sunken)
                self.frameChat.setObjectName("frameChat")
                #self.frameChat
                #end frame
                self.columnViewForm = QtWidgets.QColumnView(self.centralwidget)
                self.columnViewForm.setGeometry(QtCore.QRect(210, 80, 201, 231))
                self.columnViewForm.setAutoFillBackground(False)
                self.columnViewForm.setStyleSheet("background-color: #303030;\n"
        "border-radius: 20px;\n"
        "border-color: white;\n"
        "border-style: solid;\n"
        "border-width: 1px;")
                self.columnViewForm.setFrameShadow(QtWidgets.QFrame.Sunken)
                self.columnViewForm.setObjectName("columnViewForm")
                self.appLabel = QtWidgets.QLabel(self.centralwidget)
                self.appLabel.setGeometry(QtCore.QRect(260, 90, 101, 41))
                font = QtGui.QFont()
                font.setFamily("Diwan Kufi")
                font.setPointSize(36)
                self.appLabel.setFont(font)
                self.appLabel.setStyleSheet("color: #3665ff; background-color: none; ")
                self.appLabel.setAlignment(QtCore.Qt.AlignCenter)
                self.appLabel.setObjectName("appLabel")
                self.pushButtonLaunch = QtWidgets.QPushButton(self.centralwidget)
                self.pushButtonLaunch.setGeometry(QtCore.QRect(250, 250, 121, 32))
                font = QtGui.QFont()
                font.setFamily("Lucida Grande")
                font.setPointSize(18)
                font.setItalic(False)
                self.pushButtonLaunch.setFont(font)
                self.pushButtonLaunch.setStyleSheet("background-color: #2245b5; \n"
        "color: white; \n"
        "border-radius: 5px;\n"
        "")
                self.pushButtonLaunch.setObjectName("pushButtonLaunch")
                self.pushButtonLaunch.clicked.connect(self.launch)
                self.columnViewMain = QtWidgets.QColumnView(self.centralwidget)
                self.columnViewMain.setGeometry(QtCore.QRect(0, -29, 601, 511))
                self.columnViewMain.setStyleSheet("background-color: #303030;")
                self.columnViewMain.setAutoScrollMargin(16)
                self.columnViewMain.setObjectName("columnViewMain")
                self.lineEditName = QtWidgets.QLineEdit(self.centralwidget)
                self.lineEditName.setGeometry(QtCore.QRect(230, 160, 161, 21))
                self.lineEditName.setStyleSheet("background-color: white; \n"
        "border-radius: 5px;\n"
        "color: black;")
                self.lineEditName.setText("")
                self.lineEditName.setObjectName("lineEditName")
                self.lineEditUsername = QtWidgets.QLineEdit(self.centralwidget)
                self.lineEditUsername.setGeometry(QtCore.QRect(230, 210, 161, 21))
                self.lineEditUsername.setAutoFillBackground(False)
                self.lineEditUsername.setStyleSheet("background-color: white; \n"
        "border-radius: 5px;\n"
        "color: black;")
                self.lineEditUsername.setObjectName("lineEditUsername")
                self.labelUsername = QtWidgets.QLabel(self.centralwidget)
                self.labelUsername.setGeometry(QtCore.QRect(230, 190, 51, 20))
                font = QtGui.QFont()
                font.setFamily("Diwan Kufi")
                font.setPointSize(11)
                self.labelUsername.setFont(font)
                self.labelUsername.setStyleSheet("color: white; background-color: none; ")
                self.labelUsername.setAlignment(QtCore.Qt.AlignCenter)
                self.labelUsername.setObjectName("labelUsername")
                self.labelName = QtWidgets.QLabel(self.centralwidget)
                self.labelName.setGeometry(QtCore.QRect(230, 140, 31, 20))
                font = QtGui.QFont()
                font.setFamily("Diwan Kufi")
                font.setPointSize(11)
                self.labelName.setFont(font)
                self.labelName.setStyleSheet("color: white; background-color: none; ")
                self.labelName.setAlignment(QtCore.Qt.AlignCenter)
                self.labelName.setObjectName("labelName")
                #error label
                self.errorLabel = QtWidgets.QLabel(self.centralwidget)
                self.errorLabel.setGeometry(QtCore.QRect(220, 290, 181, 20))
                font = QtGui.QFont()
                font.setFamily("Diwan Kufi")
                font.setPointSize(13)
                self.errorLabel.setFont(font)
                self.errorLabel.setStyleSheet("color: red; background-color: none;")
                self.errorLabel.setText("")
                self.errorLabel.setAlignment(QtCore.Qt.AlignCenter)
                self.errorLabel.setObjectName("errorLabel")
                #end error lable
                self.columnViewMain.raise_()
                self.columnViewForm.raise_()
                self.appLabel.raise_()
                self.pushButtonLaunch.raise_()
                self.lineEditName.raise_()
                self.lineEditUsername.raise_()
                self.labelUsername.raise_()
                self.labelName.raise_()
                self.errorLabel.raise_()
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
                self.menubar.setObjectName("menubar")
                MainWindow.setMenuBar(self.menubar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "Relay"))
                self.appLabel.setText(_translate("MainWindow", "Relay"))
                self.pushButtonLaunch.setText(_translate("MainWindow", "Launch"))
                self.labelUsername.setText(_translate("MainWindow", "username"))
                self.labelName.setText(_translate("MainWindow", "name"))
        
        def launch(self):
                name = self.lineEditName.text()
                username = self.lineEditUsername.text()

                if (name == "" and username == ""):
                        self.errorLabel.setText("Name and Username!")
                elif (name == "" and username != ""):
                         self.errorLabel.setText("Name Required")
                elif (name != "" and username == ""):
                         self.errorLabel.setText("Username Required")
                else:
                    self.frameChat.show()

        #def clearLogin(self):





if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())